### ISSUE TITLE
レスポンスを明示的に通知したい

### ISSUE THREAD

**Issue by takenokoroid** [botan-party/hansel#1]
# なぜ
Discordからの起動・停止のレスポンスがないと不安になる。
また、インスタンス起動ごとにIPが変わるため、IPを通知しないと接続できない。
# 希望通知内容
- IPアドレス
- 起動完了の旨

**Comment by Sut103** [comment]
## ほしいパターン
### 起動時
* 起動に成功した
* 既に起動していた
* 起動に失敗した
* IPアドレスの変更通知
### 停止時
* 停止に成功した
* 既に停止していた
* 停止に失敗した(管理者メンション?)

**Comment by Sut103** [comment]
- 起動/終了の結果に関しては`CurrentState` の `Name`を使えそう？
- `Name` の値は4つ確認
  - pending
  - running
  - stopping
  - stopped
- ただ、この値はあくまでコマンドを叩いた時点の状態を返すため、実行時のレスポンスはあまり参考にならないのかもしれない

https://github.com/shokkunrf/tetona/blob/c137023bdf08e9bf38f4939da2be59158afcec73/main.go#L26-L29

**Comment by Sut103** [comment]
- [wait](https://docs.aws.amazon.com/cli/latest/reference/ec2/wait/index.html)コマンドを使うと、起動/終了を待てるみたい。
  - これで待機させれば、起動/終了が完了した時点で通知できそう。

**Comment by Sut103** [comment]
今のところの方針をまとめるとこんな感じ。
### 起動時
* 起動に成功した
  * waitコマンドを使って起動を待って通知
* 既に起動していた
  * 起動コマンド実行時、`running` が返ってきたら通知
* 起動に失敗した
  * awsコマンドが失敗したときに `log.Fatalln()` しないで通知する
    * goroutineが終わるだけなのでFatalいらない気がする。
* IPアドレスの変更通知
  * wait明けにawsコマンドでインスタンスのステータスを確認すればとれる？
### 停止時
* 停止に成功した
  * waitコマンドを使って終了を待って通知
* 既に停止していた
  * 終了コマンド実行時、`stopped` が返ってきたら通知
* 停止に失敗した(管理者メンション?)
  * awsコマンドが失敗したときに `log.Fatalln()` しないで通知する
    * goroutineが終わるだけなのでFatalいらない気がする。

### 懸念
1. `pending` で起動した場合、`stopping` で終了した場合はどうなるんだろう...
2. `stopping` で起動した場合、`pending` で終了した場合はどうなるんだろう...

**Comment by Sut103** [comment]
### 懸念 1. `pending` で起動した場合、`stopping` で終了した場合について
* そういえばこんなものがあった
https://github.com/shokkunrf/tetona/blob/c137023bdf08e9bf38f4939da2be59158afcec73/main.go#L30-L33
* `CurrentState` が `pending` で、`PreviousState` が `stopped` or `pending` だったら既に起動準備中ってことにしよう(起動コマンドの場合)
* (そこまで厳密にする必要あるの...?)

**Comment by Sut103** [comment]
### 懸念2. `stopping` で起動した場合、`pending` で終了した場合について
* 試しに両方のパターンを実施してみた
* ここまでに提示したパターンで事足りそうだ。

**stoppingで起動 --> エラーになる**
```
An error occurred (IncorrectInstanceState) when calling the StartInstances operation: The instance 'i-xxxxxxxxxxxxxxxxx' is not in a state from which it can be started.
```

**pendingで終了 --> できる**
```
{
    "StoppingInstances": [
        {
            "CurrentState": {
                "Code": 64,
                "Name": "stopping"
            },
            "InstanceId": "i-xxxxxxxxxxxxxxxxx",
            "PreviousState": {
                "Code": 0,
                "Name": "pending"
            }
        }
    ]
}
```

**Comment by Sut103** [comment]
* IPアドレスはこれで取れそう
```
$ aws ec2 describe-instances --instance-ids i-xxxxxxxxxxxxxxxxx --query 'Reservations[].Instances[].{publicip:PublicIpAddress}'
```

* こうなる
```
[
    {
        "publicip": "1.1.1.1"
    }
]
```
