### ISSUE TITLE
インスタンス起動時のIP取得までの待機時間が長い

### ISSUE THREAD

**Issue by shokkunrf** [botan-party/hansel#13]
AWSコンソールでは、インスタンスの起動に成功した時点でIPが取得できてたので待機しなくていいかもしれない
もしくは1分より短くていい

**Comment by Sut103** [comment]
起動直後にIP取得をすると失敗することがあったため、現状は適当な待機時間を設けている事情がある。
ただ、指摘の通り1分も待つ必要はないと思われる。実用性も考えると5秒程度のsleepが妥当か。
